import requests
import uuid
from datetime import datetime, timedelta
from app.models import Payment, Subscription, db
from flask import current_app

# Platega: JSON over HTTPS, auth via X-MerchantId + X-Secret headers.
# Docs: https://docs.platega.io/
PLATEGA_API_URL = "https://app.platega.io"
CRYPTOBOT_API_URL = "https://pay.crypt.bot/api"


def _platega_credentials():
    """
    Returns (merchant_id, secret). Accepts new PLATEGA_MERCHANT_ID/PLATEGA_SECRET
    names and falls back to the legacy PLATEGA_SHOP_ID/PLATEGA_API_KEY.
    """
    merchant_id = current_app.config.get('PLATEGA_MERCHANT_ID') or current_app.config.get('PLATEGA_SHOP_ID')
    secret = current_app.config.get('PLATEGA_SECRET') or current_app.config.get('PLATEGA_API_KEY')
    return merchant_id, secret


def create_platega_payment(user, plan, subscription_id):
    """
    Creates a transaction via Platega POST /v2/transaction/process.
    Returns (payment_url, transaction_id) or (None, None) if unavailable.
    The transaction id is generated by Platega and used later for status checks.
    """
    merchant_id, secret = _platega_credentials()
    if not merchant_id or not secret:
        print("[Payment] Platega not configured (need PLATEGA_MERCHANT_ID / PLATEGA_SECRET).")
        return None, None

    base = current_app.config.get('WEBHOOK_URL', 'http://localhost:5000').rstrip('/')
    # Correlate the callback/status with our subscription via payload.
    payload_ref = f"sub_{subscription_id}_{uuid.uuid4().hex[:8]}"

    headers = {
        "X-MerchantId": merchant_id,
        "X-Secret": secret,
        "Content-Type": "application/json",
    }
    body = {
        "paymentDetails": {
            "amount": plan['price'],
            "currency": "RUB",
        },
        "description": f"VOLTA VPN: {plan['name']}",
        "return": f"{base}/dashboard",
        "failedUrl": f"{base}/dashboard",
        "payload": payload_ref,
        "metadata": {
            "userId": str(getattr(user, 'telegram_id', None) or user.id),
            "userName": user.username or f"user_{user.id}",
        },
    }

    try:
        response = requests.post(
            f"{PLATEGA_API_URL}/v2/transaction/process",
            json=body, headers=headers, timeout=15,
        )
        try:
            data = response.json()
        except ValueError:
            print(f"[Payment] Platega non-JSON (HTTP {response.status_code}): {response.text[:200]}")
            return None, None

        tx_id = data.get('transactionId')
        pay_url = data.get('url')
        if response.ok and tx_id and pay_url:
            payment = Payment(
                user_id=user.id,
                amount=plan['price'],
                plan=plan['name'],
                payment_method='platega',
                external_id=str(tx_id),
                status='pending',
            )
            db.session.add(payment)
            db.session.commit()
            return pay_url, str(tx_id)

        print(f"[Payment] Platega create failed (HTTP {response.status_code}): {str(data)[:200]}")
    except Exception as e:
        print(f"[Payment] Platega API error: {e}")

    return None, None

def create_cryptobot_payment(user, plan, subscription_id):
    """
    Creates an invoice using CryptoBot API (@CryptoBot / CryptoPay).
    Returns (payment_url, invoice_id) or (None, None) if unavailable.
    """
    api_token = current_app.config.get('CRYPTOBOT_API_TOKEN')
    if not api_token:
        print("[Payment] CryptoBot not configured (need CRYPTOBOT_API_TOKEN).")
        return None, None

    payload_ref = f"sub_{subscription_id}_{uuid.uuid4().hex[:8]}"
    headers = {"Crypto-Pay-API-Token": api_token, "Content-Type": "application/json"}
    payload = {
        "amount": str(plan['price']),
        "currency_type": "fiat",
        "fiat": "RUB",
        "accepted_assets": "USDT,TON,BTC",
        "description": f"VOLTA VPN: {plan['name']}",
        "payload": payload_ref,
    }
    try:
        response = requests.post(f"{CRYPTOBOT_API_URL}/createInvoice", json=payload, headers=headers, timeout=15)
        try:
            data = response.json()
        except ValueError:
            print(f"[Payment] CryptoBot non-JSON (HTTP {response.status_code}): {response.text[:200]}")
            return None, None
        if data.get('ok') and data.get('result'):
            invoice = data['result']
            inv_id = str(invoice.get('invoice_id'))
            payment = Payment(
                user_id=user.id,
                amount=plan['price'],
                plan=plan['name'],
                payment_method='cryptobot',
                external_id=inv_id,
                status='pending'
            )
            db.session.add(payment)
            db.session.commit()
            return invoice.get('pay_url') or invoice.get('bot_invoice_url'), inv_id
        print(f"[Payment] CryptoBot create failed: {str(data)[:200]}")
    except Exception as e:
        print(f"[Payment] CryptoBot API error: {e}")

    return None, None

def check_payment_status(external_id, method):
    """
    Checks payment status and activates user subscription if paid.
    """
    payment = Payment.query.filter_by(external_id=str(external_id)).first()
    if not payment:
        return 'pending'

    if payment.status == 'paid':
        return 'paid'

    is_paid = False

    if method == 'platega':
        merchant_id, secret = _platega_credentials()
        if merchant_id and secret:
            headers = {"X-MerchantId": merchant_id, "X-Secret": secret}
            try:
                response = requests.get(f"{PLATEGA_API_URL}/transaction/{external_id}", headers=headers, timeout=15)
                data = response.json()
                # Platega statuses: PENDING / CANCELED / CONFIRMED / CHARGEBACKED
                if str(data.get('status')).upper() == 'CONFIRMED':
                    is_paid = True
            except Exception as e:
                print(f"[Payment] Platega check error: {e}")

    elif method == 'cryptobot':
        api_token = current_app.config.get('CRYPTOBOT_API_TOKEN')
        if api_token:
            headers = {"Crypto-Pay-API-Token": api_token}
            try:
                response = requests.get(f"{CRYPTOBOT_API_URL}/getInvoices?invoice_ids={external_id}", headers=headers, timeout=10)
                data = response.json()
                if data.get('ok') and data.get('result') and len(data['result']) > 0:
                    if data['result'][0].get('status') == 'paid':
                        is_paid = True
            except Exception as e:
                print(f"[Payment] CryptoBot check error: {e}")

    if is_paid:
        activate_paid_subscription(payment)
        return 'paid'

    return 'pending'


def _plan_days(plan_name):
    plan_days = {
        '1 месяц': 30,
        '2 месяца': 60,
        '3 месяца': 90,
        '6 месяцев': 180,
        '12 месяцев': 360,
    }
    days = plan_days.get(plan_name)
    if days is None:
        import re
        m = re.match(r'\s*(\d+)', plan_name or '')
        months = int(m.group(1)) if m else 1
        days = months * 30
    return days


def activate_paid_subscription(payment):
    """
    Marks the payment paid and extends/creates the user's subscription.
    Safe to call from both status polling and the Platega callback.
    """
    if payment.status == 'paid':
        return
    payment.status = 'paid'
    payment.paid_at = datetime.utcnow()

    days_to_add = _plan_days(payment.plan)
    sub = Subscription.query.filter_by(user_id=payment.user_id).order_by(Subscription.created_at.desc()).first()

    if sub and sub.is_active and not sub.is_expired():
        sub.end_date = sub.end_date + timedelta(days=days_to_add)
    else:
        if not sub:
            sub = Subscription(user_id=payment.user_id, plan=payment.plan, end_date=datetime.utcnow() + timedelta(days=days_to_add))
            db.session.add(sub)
        else:
            sub.plan = payment.plan
            sub.start_date = datetime.utcnow()
            sub.end_date = datetime.utcnow() + timedelta(days=days_to_add)
            sub.is_active = True
            sub.payment_status = 'paid'

    db.session.commit()
    return sub

